### ISSUE TITLE
Deployment of crds documentation (developer focus)

### ISSUE THREAD

**Issue by cthtrifork** [trifork/cheetah-feedback#10]
Topics
Indices
etc.

under kafka, opensearch and flink in:
https://docs.cheetah.trifork.dev/documentation/readme.html

also link to helm charts for how to guides

**Comment by KristianTrifork** [comment]
Need a bit more information about this issue. Unsure what is needed / wanted.

**Comment by AndersBennedsgaard** [comment]
Kafka topics: https://docs.cheetah.trifork.dev/documentation/kafka/development/cluster.html
