### ISSUE TITLE
[Feature]: Support Flink Version 1.18 - September

### ISSUE THREAD

**Issue by MartinCarpMBC** [trifork/cheetah-feedback#20]
### Tell us about the feature

The current Flink setup uses a Flink version which can only support Java 11. 
Java 11 exits active supports in September 2023.
Coincidentally, Flink releases version 1.18 in September, which support Java 17. (The new LTS)

To ensure that we keep running on an actively supported version of Java, it would be beneficial to update to this Flink version as quickly as possible.

**Comment by rkthtrifork** [comment]
Currently waiting for a new release of the OpenSearch connector to ensure everything is up-to-date and compatible
